#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def admin_client_credentials():
oauth:
  clients:
    admin:
      secret: #@ data.values.admin.client_secret
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-admin-client-credentials
type: Opaque
stringData:
  admin_client_credentials.yml: #@ yaml.encode(admin_client_credentials())
